version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout

  test:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run:
          name: PWD
          command: pwd
      - run:
          name: Version
          command: php -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

